name: Build and Push to Docker Hub

on:
  push:
    branches:
      - main 

permissions:
  contents: read

env:
  DOCKERHUB_REPO: sohampa/php-backend-laravel

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push image
      - name: Build and Push Docker Image
        run: |
          IMAGE_TAG=${{ github.sha }}
          echo "Building image: ${{ env.DOCKERHUB_REPO }}:$IMAGE_TAG"

          docker build -t ${{ env.DOCKERHUB_REPO }}:$IMAGE_TAG .
          docker push ${{ env.DOCKERHUB_REPO }}:$IMAGE_TAG

      # (Optional) Tag as "latest"
      - name: Tag as latest
        run: |
          docker tag ${{ env.DOCKERHUB_REPO }}:${{ github.sha }} ${{ env.DOCKERHUB_REPO }}:latest
          docker push ${{ env.DOCKERHUB_REPO }}:latest
